### use balance 1
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": 1000000000,
  "amount": 1000
}

### use balance 2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": 1000000002,
  "amount": 1000
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "799459d1b6fa4f469a544f772c34fcac",
  "accountNumber": 1000000000,
  "amount": 1000
}

### get transaction
GET http://localhost:8080/transaction/08e3c25503274d2cb2636a1062fb82ec
