### use balance 1
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": 1000000002,
  "amount": 1000
}

### use balance 2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": 1000000002,
  "amount": 1000
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "c9f310b44b234c21a9d534f5e8a0e21d",
  "accountNumber": 1000000001,
  "amount": 1000
}

### get transaction
GET http://localhost:8080/transaction/ebb6064674dc453d9689144248db048d
